baseURL = 'https://harrywang29.github.io/'
languageCode = 'zh-cn'
title = '人渣29的小窝'
theme = 'hugo-coder'
googleAnalytics = 'G-JS09HCGHMW'

[params]
author = "Harry Wang"
description = "一个不怎么样的程序员"
keywords = "blog,developer,personal"
info = ["golang", "c/c++", "python"]
#gravatar = "wrz890829@gmail.com"
colorScheme = "auto"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/HarryWang29/"

[[menu.main]]
  name = "tech"
  weight = 1
  url  = "tech/"